### ISSUE TITLE
cannot load plugin

### ISSUE THREAD

**Issue by lightbringer79** [AardStarling/Search-and-Destroy-v2.0-beta#2]
[WARNING] C:\Users\aaron\Desktop\MUSHclient\worlds\plugins\Search_and_Destroy_v2_beta.xml
Line   43: Attribute name 'data-pjax-transient' not followed by '=' (Cannot load)

**Comment by jmreynolds** [comment]
Current version is working for me -  have you tried uninstalling it and reinstalling it?

**Comment by lightbringer79** [comment]
Yes, seems I had something interfering with it.
